name: clang-format check

# only run most recent workflow in branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths-ignore:
    - README.md
    types: [ opened, reopened, synchronize ]

permissions: read-all

jobs:
  formatting-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run clang-format style check.
      uses: DoozyX/clang-format-lint-action@v0.16.2
      with:
        clangFormatVersion: 14